# ./Dockerfile.dev

FROM node:14-buster-slim

#RUN apt update && apt upgrade -y && \
    #apt install gcc g++ make python git libc6-dev build-essential libpng-dev \
    #libjpeg-dev libvips-dev libvips musl-dev node-gyp pngquant webp -y
RUN yarn global add gatsby-cli

# The port gatsby runs on
WORKDIR /app
COPY ./package.json /app
COPY ./yarn.lock /app
COPY . /app
