version: "3"
services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    command: bash -c "yarn && yarn clean && yarn start"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
